name: Build
on:
  workflow_call:
    inputs:
      python-versions:
        required: false
        type: string
        default: '["3.12", "3.13", "3.14", "3.15"]'
      os:
        required: true
        type: string
      dist:
        description: "sdist or wheel"
        required: true
        type: string
      pure-python:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build ${{ inputs.dist }} (${{ inputs.os }} - ${{ matrix.python-version }})
    runs-on: ${{ inputs.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: false
          python-version: ${{ matrix.python-version }}

      - name: Build ${{ inputs.dist }}
        env:
          VSREMOTE_BUILD_PURE_PYTHON: ${{ inputs.pure-python }}
        run: uv build --${{ inputs.dist }}

      - name: Repair wheel (Linux)
        if: runner.os == 'Linux' && !inputs.pure-python && inputs.dist == 'wheel'
        run: |
          uvx --with patchelf auditwheel repair --strip dist/*.whl -w repaired_wheels
          rm dist/*.whl
          mv repaired_wheels/*.whl dist/

      - name: Upload ${{ inputs.dist }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist-${{ inputs.dist }}-${{ inputs.os }}-${{ matrix.python-version }}
          path: dist/${{ inputs.dist == 'sdist' && '*.tar.gz' || '*.whl' }}
