name: CD

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build-sdist:
    uses: ./.github/workflows/cd-build.yml
    with:
      python-versions: '["3.12"]'
      os: ubuntu-slim
      dist: sdist

  build-generic:
    uses: ./.github/workflows/cd-build.yml
    with:
      python-versions: '["3.12"]'
      os: ubuntu-slim
      dist: wheel
      pure-python: true

  build-windows:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: windows-2025-vs2026
      dist: wheel

  build-linux:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: ubuntu-22.04
      dist: wheel

  build-macos:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: macos-15
      dist: wheel

  publish:
    name: Publish PyPI
    needs:
      - build-sdist
      - build-generic
      - build-windows
      - build-linux
      - build-macos
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/vsremote

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
