name: CD

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-sdist:
    uses: ./.github/workflows/cd-build.yml
    with:
      python-versions: '["3.12"]'
      os: ubuntu-slim
      dist: sdist

  build-windows:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: windows-2025-vs2026
      dist: wheel

  build-linux:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: ubuntu-22.04
      dist: wheel

  build-linux-aarch64:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: ubuntu-22.04-arm
      dist: wheel

  build-macos:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: macos-15
      dist: wheel

  build-macos-intel:
    uses: ./.github/workflows/cd-build.yml
    with:
      os: macos-15-intel
      dist: wheel

  publish:
    name: Publish PyPI
    needs:
      - build-sdist
      - build-windows
      - build-linux
      - build-linux-aarch64
      - build-macos
      - build-macos-intel
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/vsremote

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
